const COLOR_FORMAT_HEX = 'hexa',
  COLOR_FORMAT_RGB = 'rgba',
  COLOR_FORMAT_HSV = 'hsva',
  COLOR_MODE_SIMPLE = 0,
  COLOR_MODE_FULL = 1

export {
  COLOR_FORMAT_HEX,
  COLOR_FORMAT_RGB,
  COLOR_FORMAT_HSV,
  COLOR_MODE_SIMPLE,
  COLOR_MODE_FULL
}
