const BOARDS_LOCALSTORAGE_NAME = 'mqtt-dash-boards',
  WIDGETS_LOCALSTORAGE_NAME = 'mqtt-dash-widgets',
  CLIENTS_LOCAL_STORAGE_NAME = 'dasher-clients',
  WIDGET_STATUS_DISABLED = 0,
  WIDGET_STATUS_ENABLED = 1

export {
  BOARDS_LOCALSTORAGE_NAME,
  WIDGETS_LOCALSTORAGE_NAME,
  WIDGET_STATUS_DISABLED,
  WIDGET_STATUS_ENABLED,
  CLIENTS_LOCAL_STORAGE_NAME
}
