const BOARDS_LOCALSTORAGE_NAME = 'mqtt-tiles-boards',
  CLIENTS_LOCAL_STORAGE_NAME = 'mqtt-tiles-clients',
  WIDGET_STATUS_DISABLED = 0,
  WIDGET_STATUS_ENABLED = 1,
  WIDGET_PAYLOAD_TYPE_STRING = 0,
  WIDGET_PAYLOAD_TYPE_JSON = 1,
  WIDGET_PAYLOAD_TYPE_NUMBER = 2,
  WIDGET_RANGE_VALUE_CURRENT_MODE = 0,
  WIDGET_RANGE_VALUE_DATASOURCE_MODE = 1

export {
  BOARDS_LOCALSTORAGE_NAME,
  WIDGET_STATUS_DISABLED,
  WIDGET_STATUS_ENABLED,
  CLIENTS_LOCAL_STORAGE_NAME,
  WIDGET_PAYLOAD_TYPE_STRING,
  WIDGET_PAYLOAD_TYPE_JSON,
  WIDGET_PAYLOAD_TYPE_NUMBER,
  WIDGET_RANGE_VALUE_CURRENT_MODE,
  WIDGET_RANGE_VALUE_DATASOURCE_MODE
}
