const BOARDS_LOCALSTORAGE_NAME = 'mqtt-tiles-boards',
  WIDGETS_LOCALSTORAGE_NAME = 'mqtt-tiles-widgets',
  CLIENTS_LOCAL_STORAGE_NAME = 'mqtt-tiles-clients',
  WIDGET_STATUS_DISABLED = 0,
  WIDGET_STATUS_ENABLED = 1,
  WIDGET_PAYLOAD_TYPE_STRING = 0,
  WIDGET_PAYLOAD_TYPE_JSON = 1

export {
  BOARDS_LOCALSTORAGE_NAME,
  WIDGETS_LOCALSTORAGE_NAME,
  WIDGET_STATUS_DISABLED,
  WIDGET_STATUS_ENABLED,
  CLIENTS_LOCAL_STORAGE_NAME,
  WIDGET_PAYLOAD_TYPE_STRING,
  WIDGET_PAYLOAD_TYPE_JSON
}
